# configs/components.yaml
selectors:
  # 动态数据选择器
  less:
    name: less
    params:
      cache_dir: ../dataflex_saves/less_output
      gradient_type: adamw
      proj_dim: 4096
      seed: 123

  loss:
    name: loss
    params:
      cache_dir: ../dataflex_saves/loss_output
      focus: "medium"

  delta_loss:
    name: delta_loss
    params:
      cache_dir: ../dataflex_saves/delta_loss_output
      window_size: 0.2

  custom:
    name: custom
    params:
      cache_dir: ../dataflex_saves/custom_output

mixers:
  # 动态数据混合器
  random:
    name: random
    params:
      seed: 42

weighters:
  # 动态数据加权器
  loss:
    name: loss
    params:
      strategy: linupper # choices: [linupper, uniform, quadratic, extremes]
      delta: 1.0
  
  custom:
    name: custom
    params:
      strategy: uniform